name: meteo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^7.0.1
  flutter_native_splash: ^2.4.0
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/soleil-nuage.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/soleil-nuage.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/soleil-nuage.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/soleil-nuage.png"

flutter_native_splash:
  color: "#42a5f5"
  image_web: "assets/images/soleil-nuage.png"
